INSERT INTO tickets (title, description, customer_email, priority, status) VALUES
('Login page returning 500', 'Users are reporting that the login page returns a 500 error when clicking submit.', 'user1@example.com', 'HIGH', 'OPEN'),
('Password reset email not sending', 'I requested a password reset 30 minutes ago and have not received the email.', 'user2@example.com', 'HIGH', 'IN_PROGRESS'),
('How to update billing address?', 'Can someone guide me on where to update my billing address in the dashboard?', 'user3@example.com', 'LOW', 'RESOLVED'),
('App crashes on iOS 17', 'The mobile app crashes immediately after launch on my iPhone running iOS 17.', 'user4@example.com', 'HIGH', 'OPEN'),
('Feature request: Dark Mode', 'It would be great to have a dark mode option for late-night working.', 'user5@example.com', 'LOW', 'OPEN'),
('Typo on pricing page', 'There is a spelling mistake in the enterprise tier description.', 'user6@example.com', 'LOW', 'RESOLVED'),
('Cannot download monthly report', 'Clicking the download button does nothing. Browser console shows CORS error.', 'user7@example.com', 'MEDIUM', 'IN_PROGRESS'),
('Account locked', 'My account was locked after too many failed attempts, please unlock.', 'user8@example.com', 'HIGH', 'RESOLVED'),
('Question about API rate limits', 'What is the rate limit for the /v1/users endpoint?', 'user9@example.com', 'MEDIUM', 'RESOLVED'),
('Refund request', 'I was charged twice for my subscription this month.', 'user10@example.com', 'HIGH', 'OPEN'),
('Dashboard slow to load', 'The main dashboard takes over 10 seconds to load the widgets.', 'user11@example.com', 'MEDIUM', 'IN_PROGRESS'),
('Add PayPal as payment method', 'Will you support PayPal in the future?', 'user12@example.com', 'LOW', 'OPEN'),
('Cannot invite new users', 'The "Invite User" button is grayed out for me, even though I am an admin.', 'user13@example.com', 'HIGH', 'IN_PROGRESS'),
('Integration with Slack', 'How do I set up the Slack integration for notifications?', 'user14@example.com', 'MEDIUM', 'RESOLVED'),
('Data export is empty', 'The CSV export for last month has no rows.', 'user15@example.com', 'HIGH', 'OPEN'),
('Error saving profile', 'Getting a validation error on my phone number even though it is correct.', 'user16@example.com', 'MEDIUM', 'OPEN'),
('Renew subscription link broken', 'Clicking the renewal link in the email takes me to a 404 page.', 'user17@example.com', 'HIGH', 'IN_PROGRESS'),
('How to delete project?', 'I created a test project but cannot find the delete button.', 'user18@example.com', 'LOW', 'RESOLVED'),
('Two-factor auth not working', 'Not receiving the SMS codes for 2FA.', 'user19@example.com', 'HIGH', 'OPEN'),
('Update company name', 'Need to change our registered company name on the invoice.', 'user20@example.com', 'MEDIUM', 'RESOLVED'),
('Webhooks failing', 'Our webhooks have been failing with timeout errors for the past hour.', 'user21@example.com', 'HIGH', 'IN_PROGRESS'),
('Mobile responsive issue', 'The header menu overlaps with content on small screens.', 'user22@example.com', 'LOW', 'OPEN'),
('Custom domain setup', 'Need help pointing my domain to your servers.', 'user23@example.com', 'MEDIUM', 'RESOLVED'),
('Increase storage limit', 'We are nearing our storage limit, how do we upgrade?', 'user24@example.com', 'MEDIUM', 'IN_PROGRESS'),
('Missing invoices', 'I cannot find the invoices for Jan and Feb 2026.', 'user25@example.com', 'MEDIUM', 'OPEN'),
('Feature request: Export to PDF', 'It would be helpful to export reports as PDF instead of just CSV.', 'user26@example.com', 'LOW', 'OPEN'),
('Search not returning results', 'Searching for a specific user ID returns no results even though they exist.', 'user27@example.com', 'HIGH', 'IN_PROGRESS');
