spring.application.name=backend
spring.config.import=optional:file:../.env[.properties]
spring.data.mongodb.uri=${MONGO_URI:mongodb://dbuser:dbpassword@localhost:27017/support_tickets?authSource=admin}

# Security Configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

server.port=8080
